---
- name: load version vars
  with_first_found:
    - "../vars/versions/{{ maven_color_version }}.yml"
    - ../vars/versions/default.yml
  include_vars: "{{ item }}"

- name: assert version vars
  assert:
    that:
      - "maven_color_redis_sha256sum not in (None, '')"

- name: create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: "{{ maven_color_download_dir }}"

- name: download Maven Color
  get_url:
    url: "{{ maven_color_mirror }}/{{ maven_color_redis_filename }}"
    dest: "{{ maven_color_download_dir }}/{{ maven_color_redis_filename }}"
    sha256sum: "{{ maven_color_redis_sha256sum }}"
    force: false
    use_proxy: true
    validate_certs: true
    mode: 'u=rw,go=r'

- name: install Maven Color
  become: yes
  unarchive:
    src: "{{ maven_color_download_dir }}/{{ maven_color_redis_filename }}"
    dest: "{{ maven_color_maven_home }}"
    copy: false
    owner: root
    group: root
    mode: 'go-w'
    creates: "{{ maven_color_maven_home }}/lib/ext/maven-color-core-{{ maven_color_version }}.jar"

- name: list SLF4J Simple Logger JARs
  shell: "ls --width=1 {{ maven_color_maven_home }}/lib/slf4j-simple-*.jar"
  register: slf4j_jars
  ignore_errors: yes

- name: remove SLF4J Simple Logger
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ slf4j_jars.stdout_lines }}"
